receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlphttp:
    endpoint: https://tempo-prod-12-prod-sa-east-0.grafana.net:443
    headers:
      Authorization: Basic $API_TOKEN_TEMPO

  prometheusremotewrite:
    endpoint: $ENPOINT_PROMETHEUS_REMOTE_WRITE

  prometheus:
    endpoint: "0.0.0.0:9090"

  zipkin/nontls:
    endpoint: "http://webhook.zwirtes.com/webhook/cliente1"

processors:
  batch:
    timeout: 10s

service:
  pipelines:
    metrics:
      receivers: [otlp] 
      processors: [batch]
      exporters: [prometheusremotewrite, prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp, zipkin/nontls]